### ISSUE TITLE
How do multiple queues share time?

### ISSUE THREAD

**Issue by MichelFloyd** [mbostock/queue#32]
If I create two queues:

var queue4 = queue(4);
var fifo = queue(1);

and then put tasks into each randomly, have I effectively created 5 threads? When will each get control? Anything else I should be aware of or I am outside the flight envelope here?

**Comment by MichelFloyd** [comment]
I experimented with this a bit by queueing 135 tasks onto queue4. Each of those tasks also added a task onto queue1. The result was:

queue4 runs
queue4 runs
queue4 runs
queue4 runs
fifo runs
queue4 runs
fifo runs
queue4 runs
fifo runs
etc...

So it looks like once the fifo comes into play both queues act as a fifo.

**Comment by mbostock** [comment]
This question is more appropriate for Stack Overflow than a GitHub issue; unfortunately I often don’t have time to answer support questions. These issues are intended for bug reports and feature requests.

Still, to give some hints…

JavaScript is single-threaded, so it can be misleading to think of queues as creating multiple threads. Instead, think of it as the number of asynchronous tasks that can be processed in parallel. Things only happen in parallel if your task is using callbacks internally (such as setTimeout or fs.readFile), while the JavaScript itself remains single-threaded.

If you create separate queues, they function independently. You have one queue that allows up to four tasks to proceed in parallel, and another queue that only allows tasks to proceed serially. You can’t make any statement about how the queues interact with each other because they operate independently.
