### ISSUE TITLE
Change parallelism during run time ?

### ISSUE THREAD

**Issue by Darynh** [mbostock/queue#37]
Hello !

In my program, I'm using queue-async to queue up async commands for a SSH driver, as I need to do about 50 of them. However, I cannot do more than 20 at a time, so a standard for loop doesn't work.
The thing is, as everything is very dynamic with lots of async functions here and there, I need to check if the SSH connection has been made beforehand, and if it hasn't, I just queue it up first.

My issue is that by doing so, I have to start of with a parallelism of 1 (to make sure connection has been made), therefore all of my commands execute one by one, which is rather slow. Any ideas as to how speed up the thing ?

Draft/mock code to illustrate (using promises) :

```js
var q = queue(1);
array.forEach( function (i) {
    asyncDatabaseQuery(i).then ( function (result) { 
                             if (!connected) q.defer(function (callback) { SSH.connect().then(callback); });
                             q.defer( function (callback) { asyncSSHCommand(result) });
});
```

**Comment by mbostock** [comment]
Can you connect to SSH first, before running your database queries? (That doesn’t handle the case where you lose the SSH connection and need to reconnect, but is often sufficient.) If you can, here is how I might limit the parallelism to 20:

```js
function runQueries(queries, callback) {
  sshConnect(function(error) {
    if (error) return void callback(error);
    var q = queue(20);

    queries.forEach(function(query) {
      q.defer(function(callback) {
        runDatabaseQuery(query, function(error, result) {
          if (error) return void callback(error);
          runSshCommand(result, callback);
        });
      });
    });

    q.await(callback);
  });
}
```

Note that this also ensures that the database queries are run with limited parallelism (20). In your implementation, you’re running *all* the database queries in parallel and only throttling the SSH commands. So the results of those database queries are probably sitting in memory, waiting for SSH. It probably makes sense to limit the parallelism of the database queries the same as the SSH commands, so that you only run the database query when the SSH resource is ready.

There are more complicated things you can do if you manage multiple queues. You could maybe have a serial queue (parallelism = 1) for checking whether the SSH connection is available, and then a parallel queue for subsequently running commands. But I thought I’d start with the simpler answer.

**Comment by Darynh** [comment]
Thanks for answering back !
It seems painfully obvious now that you've shown it. However, as my database queries might take some time, is it still considered good practice to open a SSH connection and leave it as that for an undetermined amount of time ?
Cheers,

**Comment by mbostock** [comment]
It depends. That’s what I was hinting at earlier—the code I posted doesn’t handle the SSH connection timing out or being disconnected.

Also, are you sure you want to run multiple commands in parallel on a single SSH connection? You might want those to be serialized anyway. Although I guess if you are backgrounding the commands you are running over SSH it’s fine to run them in parallel, though I think even in that case the commands would need to be issued serially even if the jobs are run in parallel… I dunno.

**Comment by mbostock** [comment]
Often what you want is a connection pool, like this:

```js
var connections = [];

// Runs the specified command, opening a new connection if none are available.
function runCommand(command, callback) {
  var connection = connections.pop();

  // If there’s no connection available, open one and then run this command.
  if (!connection) return void openConnection(function(error, connection) {
    if (error) return void callback(error);
    connections.push(connection);
    runCommand(command, callback);
  });

  // Otherwise, use the available connection, and then return it to the pool.
  connection.runCommand(command, function(error, result) {
    connections.push(connection); // Note: assumes the connection is still okay on error.
    callback(error, result);
  });
}
```

This assumes there’s some asynchronous function for opening a connection:

```js
function openConnection(callback) {
  …
}
```

Then, you can use queue to control the size of the connection pool. Like if you want to limit it to six open connections:

```js
var q = queue(6);

commands.forEach(function(command) {
  q.defer(runCommand, command);
});
```

Note that you probably want to close those connections when you’re done:

```js
q.await(function(error) {
  if (error) console.error(error);
  connections.forEach(function(connection) {
    connection.close();
  });
});
```

Also, you *might* want to throw away a connection if you try to run a command and it fails, because one of those failure modes is that the connection has broken. So, you could check the type of error and retry on a new connection. Or you could just assume that the connection is broken and always create a new connection, but that can end up going into an infinite loop and being a bad network citizen.

**Comment by Darynh** [comment]
Very interesting, you have shed some light and answered many questions I had :-)
However, I still struggle with the concept of connection pool : with connections.pop(), how could 6 commands could be made ? Won't the first one take the connection, thus creating a new connection for each of the other ones ? As I have only one account on the remote server, would it still be possible to use the connection pool pattern ?

My initial idea was to create an independant set of functions. Initially, I have an array, in which I run an async.each to query a database, and when I get the result from the query I run the SSH command. Without queue, the SSH connection just stopped after 20 commands in parallel have been made, which is why I used queue to limit them.
