### ISSUE TITLE
Bower Package missing build?

### ISSUE THREAD

**Issue by seancunningham** [mbostock/queue#43]
Hi there,
I'm using queue-async as both a bower component and node module, and I'm noticing a discrepancy between the packages that my webpack config is having a hard time resolving. The node module seems to be pre-built, having a build folder pre-existing when you pull the repository down -- however the bower component seems to be only available through an es6 loader. Was this intentional, or is the bower component missing a build script?

**Comment by mbostock** [comment]
AFAIK, Bower still does not support publishing generated files and so there is no way to include the generated UMD build in the release, as there is with npm. I will not be checking in the generated files to the git repository due to the overhead this adds to development; I also do not want to maintain a separate git repository to hold just the generated files, as some have done (e.g., [bower-chosen](https://github.com/harvesthq/bower-chosen)).

If you want to use the generated UMD build in the published release, please use npm or use the provided queue.zip download attached to [the latest release](https://github.com/mbostock/queue/releases/latest). Otherwise, you must build it yourself from the ES6 source using Rollup, Webpack, or your bundler of choice.
