### ISSUE TITLE
1.1.0 causing breaking changes

### ISSUE THREAD

**Issue by vicapow** [mbostock/queue#44]
I don't have the full details, but @vdumont reports having to lock down to 1.0.7 to fix an issue with queue-async. Maybe this was meant to be a major version change? see: https://github.com/mapbox/node-fontnik/pull/108

**Comment by mbostock** [comment]
There’s not sufficient information here to investigate. Can you provide more information?

**Comment by mbostock** [comment]
(This was not a major version change.)

**Comment by mbostock** [comment]
I did some digging. The problem seems to be [this line](https://github.com/mapbox/node-fontnik/blob/master/bin/build-glyphs#L25):

```js
var q = queue(Math.max(4, require('os').cpus()));
```

The problem is that os.cpus returns an array of objects, not a count:

```js
> require('os').cpus()
[ { model: 'Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz',
    speed: 3400,
    times: { user: 2604590, nice: 0, sys: 4363080, idle: 202084130, irq: 0 } },
  { model: 'Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz',
    speed: 3400,
    times: { user: 108650, nice: 0, sys: 110380, idle: 208832140, irq: 0 } },
  { model: 'Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz',
    speed: 3400,
    times: { user: 2099660, nice: 0, sys: 1423710, idle: 205527790, irq: 0 } },
  { model: 'Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz',
    speed: 3400,
    times: { user: 113050, nice: 0, sys: 103230, idle: 208834890, irq: 0 } },
  { model: 'Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz',
    speed: 3400,
    times: { user: 1989420, nice: 0, sys: 1232690, idle: 205829050, irq: 0 } },
  { model: 'Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz',
    speed: 3400,
    times: { user: 114970, nice: 0, sys: 99670, idle: 208836520, irq: 0 } },
  { model: 'Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz',
    speed: 3400,
    times: { user: 1998900, nice: 0, sys: 1291880, idle: 205760390, irq: 0 } },
  { model: 'Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz',
    speed: 3400,
    times: { user: 113670, nice: 0, sys: 99980, idle: 208837510, irq: 0 } } ]
```

So, `Math.max(4, require('os').cpus())` is NaN; you’re setting a parallelism of NaN. You want to say:

```js
var q = queue(Math.max(4, require('os').cpus().length));
```

With a parallelism of NaN, no tasks get executed. 

Previously, queue would treat any falsey parallelism as Infinity:

```js
if (!parallelism) parallelism = Infinity;
```

In 1.1.0, the check is more precise, and it coerces the value to a number so that it is compared correctly:

```js
parallelism = arguments.length ? +parallelism : Infinity;
```

Arguably, it should throw an Error if parallelism is NaN or less than 1. But sometimes it’s a pain to try to detect all the broken ways an API is used, and sometimes there are valid reasons for it to fail in well-defined ways rather than throwing an Error.

**Comment by vdumont** [comment]
Thanks @mbostock, that is indeed the fix!

**Comment by mikemorris** [comment]
Thanks for tracking this down @mbostock =)

I merged the patch from @vdumont I'll hit `npm publish` on a `v0.4.4` release as soon as CI finishes publishing binaries @vicapow
